# Generated by Django 6.0.2 on 2026-02-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField(db_index=True)),
                ('truckstop_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.FloatField(db_index=True)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('geocoded', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fuel_stations',
                'indexes': [models.Index(fields=['state', 'geocoded'], name='fuel_statio_state_d61f05_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_statio_latitud_c84538_idx'), models.Index(fields=['retail_price'], name='fuel_statio_retail__463e8c_idx')],
                'unique_together': {('truckstop_name', 'address', 'city', 'state')},
            },
        ),
    ]
